facus-blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('movie/', include('movie.urls')),
    path('music/', include('music.urls')),
    path('game/', include('game.urls')),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from game import views


app_name='game'
urlpatterns = [
    path('games', views.GameListView.as_view(), name='game-list'),
    path('game/add/', views.GameCreateView.as_view(), name='game-add'),
    path('game/<int:pk>/detail', views.GameDetailView.as_view(), name='game-detail'),
    path('game/<int:pk>/update', views.GameUpdateView.as_view(), name='game-update'),
    path('game/<int:pk>/delete', views.GameDeleteView.as_view(), name='game-delete'),
]

music/urls.py
from django.urls import path
from music import views


app_name='music'
urlpatterns = [
    path('musics', views.MusicListView.as_view(), name='music-list'),
    path('music/add/', views.MusicCreateView.as_view(), name='music-add'),
    path('music/<int:pk>/detail', views.MusicDetailView.as_view(), name='music-detail'),
    path('music/<int:pk>/update', views.MusicUpdateView.as_view(), name='music-update'),
    path('music/<int:pk>/delete', views.MusicDeleteView.as_view(), name='music-delete'),
]

proyecto_final/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

music/models.py
from django.db import models
import datetime
from user.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Music(models.Model):
    YEAR_CHOICES = []
    for r in range(1880, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r,r))
    
    name = models.CharField(max_length=40, default="", verbose_name="Nombre")
    cover = models.ImageField(upload_to='staticfiles/covers/',  null=True, blank=True, verbose_name="Poster")
    singer = models.CharField(max_length=40, default="", verbose_name="Cantante")
    year = models.IntegerField(('Año'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    plot = RichTextField(blank = True, null=True, verbose_name="Trama")
    post_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,null=True,blank=True,on_delete=models.DO_NOTHING,default="", verbose_name="Autor")


    def __str__(self):
        return f'{self.name}'

music/views.py
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from music.models import Music

class MusicListView(ListView):
    model = Music
    template_name = "music/music_list.html"


class MusicDetailView(DetailView):
    model = Music
    template_name = "music/music_detail.html"


class MusicCreateView(LoginRequiredMixin, CreateView):
    model = Music
    success_url = reverse_lazy('music:music-list')
    fields = '__all__'


class MusicUpdateView(LoginRequiredMixin, UpdateView):
    model = Music
    success_url = reverse_lazy('music:music-list')
    fields = '__all__'


class MusicDeleteView(LoginRequiredMixin, DeleteView):
    model = Music
    success_url = reverse_lazy('music:music-list')

music/templates/music/music_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}

<h2>Eliminar Música</h2>
<hr></hr>

<p>Está seguro de eliminar el tema: {{ music.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn2 btn-warning" type="submit" value="Sí, eliminar">
    <a class="btn2 btn-primary" href="{% url 'music:music-list' %}" >Cancelar</a>
</form>

{% endblock %}

music/templates/music/music_detail.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}

<p></p>
<p><h2>{{ music.name }}</h2></p>
<hr></hr>
<img height="250px" src="{{ music.cover.url }}">
<p><h4>Cantante: {{ music.singer }}</h4></p>
<p><h4>Año: {{ music.year }}</h4></p>
<h4>Descripción:</h4>
<p>{{ music.plot|safe }}</p>
<p><h4>Autor: {{ music.author }}</h4></p>
<p><h5>Posteado: {{ music.post_date | date:"d-m-Y h:m" }}</h5></p>
<p></p>



<p><a class="btn2 btn-primary" href="{% url 'music:music-list' %}">Regresar al listado</a></p>
{% endblock %}

music/templates/music/music_form.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}
{% load widget_tweaks %}


<h2>Formulario para guardar/editar Música:</h2>
<hr></hr>
<br>
        

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}

    {%for field in form%}
    <div class="form-group">
        <h4 class="control-label" for="{{ field.name }}">{{ field.label }} : </h4>
            <div class="col-sm-9">
            {{ field|add_class:'form-control' }}
            
            </div>
        <br>
        {%endfor%}
    </div>
    <br>
    

    <input type="submit" class="btn btn-primary" value="Guardar" />
    <a type="submit" class="btn btn-primary" href="{% url 'music:music-list' %}">Cancelar</a>
    
</form>

{% endblock %}

music/templates/music/music_list.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}
<hr>
<h2>Música</h2>
{% if user.is_authenticated %}
<br>
<a class="btn2 btn-primary" href="{% url 'music:music-add' %}">Agregar Música</a>
{% endif %}
<br>
<br>
<ul>
    {% for music in music_list %}
    <h5>
    <li>
        
        {{music}}
        (
        
            <a href="{% url 'music:music-detail' music.id %}">
                <i class="fa fa-eye" style="color: rgb(255, 255, 255);"> </i>
            </a>
        )
        {%  if user.is_authenticated %}
        |
        <a href="{% url 'music:music-update' music.id %}">
            <i class="fa fa-pencil" style="color: rgb(255, 255, 255);"> </i>
        </a>
        |
        <a href="{% url 'music:music-delete' music.id %}">
            <i class="fa fa-trash" style="color: rgb(255, 255, 255);"> </i>
        </a>
        
        {% endif %}
        
    </li>
    </h5>
    <p></p>
    {% endfor %}
</ul>

{% endblock %}