facus-blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('movie/', include('movie.urls')),
    path('music/', include('music.urls')),
    path('game/', include('game.urls')),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from game import views


app_name='game'
urlpatterns = [
    path('games', views.GameListView.as_view(), name='game-list'),
    path('game/add/', views.GameCreateView.as_view(), name='game-add'),
    path('game/<int:pk>/detail', views.GameDetailView.as_view(), name='game-detail'),
    path('game/<int:pk>/update', views.GameUpdateView.as_view(), name='game-update'),
    path('game/<int:pk>/delete', views.GameDeleteView.as_view(), name='game-delete'),
]

home/urls.py
from django.urls import path

from home import views

app_name='home'
urlpatterns = [
    path('', views.index, name='main'),
    path('search', views.search, name='search'),
]

movie/urls.py
from django.urls import path
from movie import views


app_name='movie'
urlpatterns = [
    path('movies', views.MovieListView.as_view(), name='movie-list'),
    path('movie/add/', views.MovieCreateView.as_view(), name='movie-add'),
    path('movie/<int:pk>/detail', views.MovieDetailView.as_view(), name='movie-detail'),
    path('movie/<int:pk>/update', views.MovieUpdateView.as_view(), name='movie-update'),
    path('movie/<int:pk>/delete', views.MovieDeleteView.as_view(), name='movie-delete'),
]

music/urls.py
from django.urls import path
from music import views


app_name='music'
urlpatterns = [
    path('musics', views.MusicListView.as_view(), name='music-list'),
    path('music/add/', views.MusicCreateView.as_view(), name='music-add'),
    path('music/<int:pk>/detail', views.MusicDetailView.as_view(), name='music-detail'),
    path('music/<int:pk>/update', views.MusicUpdateView.as_view(), name='music-update'),
    path('music/<int:pk>/delete', views.MusicDeleteView.as_view(), name='music-delete'),
]

proyecto_final/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
]

home/models.py
from django.db import models

home/views.py
from django.shortcuts import render
from django.db.models import Q
from user.models import Avatar


def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"url": avatars[0].image.url}
    return {}



def index(request):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    print('context_dict: ', context_dict)
    return render(
        request=request,
        context=context_dict,
        template_name="home/main.html"
    )


def search(request):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    if request.GET['search_param']:
        search_param = request.GET['search_param']
        query = Q(name__contains=search_param)

    return render(
        request=request,
        context=context_dict,
        template_name="home/main.html",
    )

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/img/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
        <!-- Awesome fonts -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home:main' %}">Home</a>
                <a class="navbar-brand" href="{% url 'movie:movie-list' %}">Películas</a>
                <a class="navbar-brand" href="{% url 'music:music-list' %}">Música</a>
                <a class="navbar-brand" href="{% url 'game:game-list' %}">Juegos</a>
                {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'user:user-update' %}">Editar usuario</a>
                <a class="btn btn-primary" href="{% url 'user:user-logout' %}">Cerrar Sesión</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'user:user-login' %}">Iniciar Sesión</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5"> Facus BLOG <br> </h1>
                            {% if messages %}
                                {% for message in messages %}
                                <h4><p style="color: rgb(131, 31, 0)" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p></h4>
                                {% endfor %}
                            {% endif %}
                            <div class="text-lg-start text-white">

                                {% block facus-blog_content %}

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                {% if user.is_superuser %}
        <!--            <h5><p style="color: rgb(0, 20, 131)" >SuperUser</p></h5> -->
                {% else %}
        <!--            <h5><p style="color: rgb(0, 20, 131)" >Not SuperUser</p></h5>-->
                {%endif%}
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <p class="text-muted small mb-4 mb-lg-0">&copy; FACUS </p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

home/templates/home/main.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}


{% if user.is_authenticated %}
<div class="text-center">
    <h2>Bienvenido {{ user.first_name }}</h2>
    <img height="160px" src="{{url}}" alt="">
</div>
{% endif %}

<hr></hr>
<h2>Un viaje por diversos intereses</h2>
<p></p>


{% endblock %}