facus-blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('movie/', include('movie.urls')),
    path('music/', include('music.urls')),
    path('game/', include('game.urls')),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from game import views


app_name='game'
urlpatterns = [
    path('games', views.GameListView.as_view(), name='game-list'),
    path('game/add/', views.GameCreateView.as_view(), name='game-add'),
    path('game/<int:pk>/detail', views.GameDetailView.as_view(), name='game-detail'),
    path('game/<int:pk>/update', views.GameUpdateView.as_view(), name='game-update'),
    path('game/<int:pk>/delete', views.GameDeleteView.as_view(), name='game-delete'),
]

movie/urls.py
from django.urls import path
from movie import views


app_name='movie'
urlpatterns = [
    path('movies', views.MovieListView.as_view(), name='movie-list'),
    path('movie/add/', views.MovieCreateView.as_view(), name='movie-add'),
    path('movie/<int:pk>/detail', views.MovieDetailView.as_view(), name='movie-detail'),
    path('movie/<int:pk>/update', views.MovieUpdateView.as_view(), name='movie-update'),
    path('movie/<int:pk>/delete', views.MovieDeleteView.as_view(), name='movie-delete'),
]

proyecto_final/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

movie/models.py
from django.db import models
import datetime
from user.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Movie(models.Model):
    YEAR_CHOICES = []
    for r in range(1880, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r,r))
    
    name = models.CharField(max_length=40, default="", verbose_name="Nombre")
    cover = models.ImageField(upload_to='staticfiles/covers/',  null=True, blank=True, verbose_name="Poster")
    director = models.CharField(max_length=40, default="", verbose_name="Director")
    year = models.IntegerField(('Año'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    plot = RichTextField(blank = True, null=True, verbose_name="Trama")
    post_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,null=True,blank=True,on_delete=models.DO_NOTHING,default="", verbose_name="Autor")


    def __str__(self):
        return f'{self.name}'

movie/views.py
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from movie.models import Movie

class MovieListView(ListView):
    model = Movie
    template_name = "movie/movie_list.html"


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movie/movie_detail.html"


class MovieCreateView(LoginRequiredMixin, CreateView):
    model = Movie
    success_url = reverse_lazy('movie:movie-list')
    fields = '__all__'


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    model = Movie
    success_url = reverse_lazy('movie:movie-list')
    fields = '__all__'


class MovieDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy('movie:movie-list')

movie/templates/movie/movie_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}

<h2>Eliminar Película</h2>
<hr></hr>

<p>Está seguro de eliminar la película: {{ movie.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn2 btn-warning" type="submit" value="Sí, eliminar">
    <a class="btn2 btn-primary" href="{% url 'movie:movie-list' %}" >Cancelar</a>
</form>

{% endblock %}

movie/templates/movie/movie_detail.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}

<p></p>
<p><h2>{{ movie.name }}</h2></p>
<hr></hr>
<img height="250px" src="{{ movie.cover.url }}">
<p><h4>Director: {{ movie.director }}</h4></p>
<p><h4>Año: {{ movie.year }}</h4></p>
<h4>Trama:</h4>
<p>{{ movie.plot|safe }}</p>
<p><h4>Autor: {{ movie.author }}</h4></p>
<p><h5>Posteado: {{ movie.post_date | date:"d-m-Y h:m" }}</h5></p>
<p></p>



<p><a class="btn2 btn-primary" href="{% url 'movie:movie-list' %}">Regresar al listado</a></p>
{% endblock %}

movie/templates/movie/movie_form.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}
{% load widget_tweaks %}


<h2>Formulario para guardar/editar Películas:</h2>
<hr></hr>
<br>
        

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}

    {%for field in form%}
    <div class="form-group">
        <h4 class="control-label" for="{{ field.name }}">{{ field.label }} : </h4>
            <div class="col-sm-9">
            {{ field|add_class:'form-control' }}
            
            </div>
        <br>
        {%endfor%}
    </div>
    <br>
    

    <input type="submit" class="btn btn-primary" value="Guardar" />
    <a type="submit" class="btn btn-primary" href="{% url 'movie:movie-list' %}">Cancelar</a>
    
</form>

{% endblock %}

movie/templates/movie/movie_list.html
{% extends "home/index.html" %}
{% load static %}
{% block facus-blog_content %}
<hr>
<h2>Películas</h2>
{% if user.is_authenticated %}
<br>
<a class="btn2 btn-primary" href="{% url 'movie:movie-add' %}">Agregar Película</a>
{% endif %}
<br>
<br>
<ul>
    {% for movie in movie_list %}
    <h5>
    <li>
        
        {{movie}}
        (
        
            <a href="{% url 'movie:movie-detail' movie.id %}">
                <i class="fa fa-eye" style="color: rgb(255, 255, 255);"> </i>
            </a>
        )
        {%  if user.is_authenticated %}
        |
        <a href="{% url 'movie:movie-update' movie.id %}">
            <i class="fa fa-pencil" style="color: rgb(255, 255, 255);"> </i>
        </a>
        |
        <a href="{% url 'movie:movie-delete' movie.id %}">
            <i class="fa fa-trash" style="color: rgb(255, 255, 255);"> </i>
        </a>
        
        {% endif %}
        
    </li>
    </h5>
    <p></p>
    {% endfor %}
</ul>

{% endblock %}